### ISSUE TITLE
old TODO's and clean up

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#160]
We need to implement all TODO's and clean up the code a bit:
- [ ] move constants in conversion.hpp into a enum
- [ ] change linux sscanf to something better (clang-tidy issue) (TODO)
- [ ] Silently disable raw mode if the terminal is not interactive (TODO)
- [ ] skip adding a number to ansi codes on 0 (0 is the deafult value if no value is specified)
- [ ] throw runtime errors on wrong values for ANSI functions
- [ ] optimize datatypes (use for 0 - 255 ranges uint8_t)
- [ ] make the code available for unsupported sequences in input function
- [ ] merge window and window24 together
- [ ] add screen parameter to window class (TODO)
- [ ] make a function out of the ansi code from the new prompt
- [ ] remove function names from headers

**Comment by flagarde** [comment]
> We need to implement all TODO's and clean up the code a bit:
> 
>     * [ ]  move constants in conversion.hpp into a enum
> 
>     * [X]  change linux sscanf to something better (clang-tidy issue) (TODO)
> 
>     * [x]  Silently disable raw mode if the terminal is not interactive (TODO)
> 
>     * [ ]  skip adding a number to ansi codes on 0 (0 is the deafult value if no value is specified)
> 
>     * [ ]  throw runtime errors on wrong values for ANSI functions
> 
>     * [x]  optimize datatypes (use for 0 - 255 ranges uint8_t)
> 
>     * [ ]  make the code available for unsupported sequences in input function
> 
>     * [X]  merge window and window24 together
> 
>     * [ ]  add screen parameter to window class (TODO)
> 
>     * [ ]  make a function out of the ansi code from the new prompt
> 
>     * [x]  remove function names from headers

**Comment by MCWertGaming** [comment]
Updated the list
